import Head from 'next/head'
import Router from 'next/router';
import Header from '@/components/Header/Header';


import { Formik, Form, Field } from "formik";
import * as Yup from "yup";
import Link from "next/link";
import Navbar from '@/components/Header/Navbar';
import Login from './auth/Login';
import banner from '@/components/Header/banner';






export default function Home() {
    
  return (
    <>
      <Head>
        <title>MultiDeal </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <banner />

  



      <Login />


      




      
    </>
  )
}




