import Head from 'next/head'
import Router from 'next/router';
import Header from '@/components/Header/Header';
import Image from 'next/image';


import { Formik, Form, Field } from "formik";
import * as Yup from "yup";
import Link from "next/link";
import Navbar from '@/components/Header/Navbar';
import Login from './auth/Login';
import Hero from '@/components/Header/hero';
import Footer from '@/components/Footer/Footer';
import FlashDeal from '@/components/Main/Flash Deal';
import Catagories from '@/components/ProductCatagories/Catagories';
import Banner from '@/components/Main/Banner';
import Features from '@/components/Footer/Features';
// import Register from './auth/Register';




export default function Home() {

  return (
    <>
      <Head>
        <title>MultiDeal </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Hero />

      <Catagories />
      <FlashDeal />
      <Banner />
      <Features />

      

   
      <Footer />







      {/* <Login /> */}








    </>
  )
}




