import Head from 'next/head'
import Router from 'next/router';
import Header from '@/components/Header/Header';







export default function Home() {
    
  return (
    <>
      <Head>
        <title>MultiDeal </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header className=' h-9 w-5 bg-yellow-500' />

      


      
    </>
  )
}



